### ISSUE TITLE
Explain?

### ISSUE THREAD

**Issue by analamus** [install-gentoo-cuck/4chan-auto-memer#4]
I noticed that captcha.html was heavily borrowed from https://github.com/Floens/Clover/issues/58#issue-65346787, but I still don't understand. How does [this](https://github.com/install-gentoo-cuck/4chan-auto-memer/blob/master/captcha.html#L7-L19) work?
I understand that [this](https://github.com/install-gentoo-cuck/4chan-auto-memer/blob/master/captcha.html#L7-L13) is used for the captcha, and [this](https://github.com/install-gentoo-cuck/4chan-auto-memer/blob/master/captcha.html#L11) runs the function [here](https://github.com/install-gentoo-cuck/4chan-auto-memer/blob/master/captcha.html#L15-L19), which writes a verification code to `<p id="result">` after the user correctly solves the captcha, but I don't understand _how_ it works. How are you getting the verification code for g-recaptcha-resposne?

**Comment by Guad** [comment]
That's a feature of Google's captcha. Notice the url that I called it with.

**Comment by analamus** [comment]
I still don't understand.

> Notice the url that I called it with. 

[This](https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit) one?

**Comment by Guad** [comment]
> google.com/recaptcha/api.js?**onload=onloadCallback**&render=explicit

When the captcha loads, google calls our function **onloadCallback**. Inside, we have a function google provided to display our captcha with our desired configuration. First argument is the DOM element ID where want to display the captcha and the second is our config. We can pass a callback function that gets called once the user solves the captcha. When the user does this, google calls our **dataCallback** function passing the solved captcha 'hash' as a parameter. We take that parameter and display it in <p id="result">

**Comment by analamus** [comment]
> When the user does this, google calls our dataCallback function passing the solved captcha 'hash' as a parameter. We take that parameter and display it in 

This is the part where I'm lost.

> var dataCallback = function(authResult) {

Doesn't this create a function called authResult?
If so, then how does `document.getElementById("result").innerHTML = authResult;` work?

**Comment by Guad** [comment]
> Doesn't this create a function called authResult?

Yes it does, and we passed it's name in the config in **onloadCallback**

```
var onloadCallback = function() {
    grecaptcha.render('html_element', {
                  'sitekey' : '6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc',
                  'callback' : dataCallback, // <-- Here is our captcha-is-solved function
                   });
};
```

**Comment by analamus** [comment]
I understand that `'callback' : dataCallback` runs dataCallback when the captcha is solved, I'm just confused as to where the key is coming from. Does dataCallback also contain the key/is the key passed to dataCallback?

**Comment by Guad** [comment]
The key is coming from Google. We just told them where to send it (dataCallback).

**Comment by analamus** [comment]
> We just told them where to send it (dataCallback).

Alright, I believe I understand now. Thank you for taking the time to explain. I apologize for bothering you with this non-issue.

**Comment by Guad** [comment]
Don't worry, glad you understand it.

**Comment by analamus** [comment]
Stupid question, how would I fix this up for v1/legacy?
I googled a little and came across [this](https://stackoverflow.com/questions/7261436/how-can-i-load-a-recaptcha-form-using-jquery-ajax-while-leaving-the-recaptcha-sc/7261660#7261660).
I tried changing

```
    var onloadCallback = function() {
        grecaptcha.render('html_element', {
                          'sitekey': '6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc',
                          'callback': dataCallback
        });
    };
```

to

```
    var onloadCallback = function() {
        Recaptcha.create("6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc",
                         "html_element", {
                         theme: "clean",
                         callback: dataCallback
        });
    };
```

and 
`<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"></script>`
to
`<script src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>`, but it didn't work. The captcha doesn't even display.

**Comment by Guad** [comment]
Sincerely I dunno about v1

**Comment by analamus** [comment]
Darn, that sucks. Street addresses and words are way better than burgers and sushi.
